/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as graphql from "@nestjs/graphql";
import { GraphQLError } from "graphql";
import { isRecordNotFoundError } from "../../prisma.util";
import { MetaQueryPayload } from "../../util/MetaQueryPayload";
import { Main } from "./Main";
import { MainCountArgs } from "./MainCountArgs";
import { MainFindManyArgs } from "./MainFindManyArgs";
import { MainFindUniqueArgs } from "./MainFindUniqueArgs";
import { DeleteMainArgs } from "./DeleteMainArgs";
import { MainService } from "../main.service";
@graphql.Resolver(() => Main)
export class MainResolverBase {
  constructor(protected readonly service: MainService) {}

  async _mainsMeta(
    @graphql.Args() args: MainCountArgs
  ): Promise<MetaQueryPayload> {
    const result = await this.service.count(args);
    return {
      count: result,
    };
  }

  @graphql.Query(() => [Main])
  async mains(@graphql.Args() args: MainFindManyArgs): Promise<Main[]> {
    return this.service.mains(args);
  }

  @graphql.Query(() => Main, { nullable: true })
  async main(@graphql.Args() args: MainFindUniqueArgs): Promise<Main | null> {
    const result = await this.service.main(args);
    if (result === null) {
      return null;
    }
    return result;
  }

  @graphql.Mutation(() => Main)
  async deleteMain(@graphql.Args() args: DeleteMainArgs): Promise<Main | null> {
    try {
      return await this.service.deleteMain(args);
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new GraphQLError(
          `No resource was found for ${JSON.stringify(args.where)}`
        );
      }
      throw error;
    }
  }
}
