/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import { PrismaService } from "../../prisma/prisma.service";
import { Prisma, Main as PrismaMain } from "@prisma/client";

export class MainServiceBase {
  constructor(protected readonly prisma: PrismaService) {}

  async count(args: Omit<Prisma.MainCountArgs, "select">): Promise<number> {
    return this.prisma.main.count(args);
  }

  async mains(args: Prisma.MainFindManyArgs): Promise<PrismaMain[]> {
    return this.prisma.main.findMany(args);
  }
  async main(args: Prisma.MainFindUniqueArgs): Promise<PrismaMain | null> {
    return this.prisma.main.findUnique(args);
  }
  async createMain(args: Prisma.MainCreateArgs): Promise<PrismaMain> {
    return this.prisma.main.create(args);
  }
  async updateMain(args: Prisma.MainUpdateArgs): Promise<PrismaMain> {
    return this.prisma.main.update(args);
  }
  async deleteMain(args: Prisma.MainDeleteArgs): Promise<PrismaMain> {
    return this.prisma.main.delete(args);
  }
}
