/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as common from "@nestjs/common";
import * as swagger from "@nestjs/swagger";
import { isRecordNotFoundError } from "../../prisma.util";
import * as errors from "../../errors";
import { Request } from "express";
import { plainToClass } from "class-transformer";
import { ApiNestedQuery } from "../../decorators/api-nested-query.decorator";
import { MainService } from "../main.service";
import { MainCreateInput } from "./MainCreateInput";
import { Main } from "./Main";
import { MainFindManyArgs } from "./MainFindManyArgs";
import { MainWhereUniqueInput } from "./MainWhereUniqueInput";
import { MainUpdateInput } from "./MainUpdateInput";

export class MainControllerBase {
  constructor(protected readonly service: MainService) {}
  @common.Post()
  @swagger.ApiCreatedResponse({ type: Main })
  async createMain(@common.Body() data: MainCreateInput): Promise<Main> {
    return await this.service.createMain({
      data: data,
      select: {
        createdAt: true,
        id: true,
        updatedAt: true,
      },
    });
  }

  @common.Get()
  @swagger.ApiOkResponse({ type: [Main] })
  @ApiNestedQuery(MainFindManyArgs)
  async mains(@common.Req() request: Request): Promise<Main[]> {
    const args = plainToClass(MainFindManyArgs, request.query);
    return this.service.mains({
      ...args,
      select: {
        createdAt: true,
        id: true,
        updatedAt: true,
      },
    });
  }

  @common.Get("/:id")
  @swagger.ApiOkResponse({ type: Main })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  async main(
    @common.Param() params: MainWhereUniqueInput
  ): Promise<Main | null> {
    const result = await this.service.main({
      where: params,
      select: {
        createdAt: true,
        id: true,
        updatedAt: true,
      },
    });
    if (result === null) {
      throw new errors.NotFoundException(
        `No resource was found for ${JSON.stringify(params)}`
      );
    }
    return result;
  }

  @common.Patch("/:id")
  @swagger.ApiOkResponse({ type: Main })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  async updateMain(
    @common.Param() params: MainWhereUniqueInput,
    @common.Body() data: MainUpdateInput
  ): Promise<Main | null> {
    try {
      return await this.service.updateMain({
        where: params,
        data: data,
        select: {
          createdAt: true,
          id: true,
          updatedAt: true,
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }

  @common.Delete("/:id")
  @swagger.ApiOkResponse({ type: Main })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  async deleteMain(
    @common.Param() params: MainWhereUniqueInput
  ): Promise<Main | null> {
    try {
      return await this.service.deleteMain({
        where: params,
        select: {
          createdAt: true,
          id: true,
          updatedAt: true,
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }
}
